// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4Ew3n8wxmCG7mbxc9GVcIgQgcyrUOJM',
    appId: '1:698678244062:web:bf36d2d9e186793980c84f',
    messagingSenderId: '698678244062',
    projectId: 'consearch-52394',
    authDomain: 'consearch-52394.firebaseapp.com',
    storageBucket: 'consearch-52394.firebasestorage.app',
    measurementId: 'G-E5N1BTYEYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgU1kkQv8bB3wiJ3O7PFW-G5akl7SytE',
    appId: '1:698678244062:android:4f364c96915931fa80c84f',
    messagingSenderId: '698678244062',
    projectId: 'consearch-52394',
    storageBucket: 'consearch-52394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCybWpUii4DWsMzXBBRLpKlF1IfxrDo_kE',
    appId: '1:698678244062:ios:79b207360550084480c84f',
    messagingSenderId: '698678244062',
    projectId: 'consearch-52394',
    storageBucket: 'consearch-52394.firebasestorage.app',
    iosBundleId: 'com.example.consearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCybWpUii4DWsMzXBBRLpKlF1IfxrDo_kE',
    appId: '1:698678244062:ios:79b207360550084480c84f',
    messagingSenderId: '698678244062',
    projectId: 'consearch-52394',
    storageBucket: 'consearch-52394.firebasestorage.app',
    iosBundleId: 'com.example.consearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu4Ew3n8wxmCG7mbxc9GVcIgQgcyrUOJM',
    appId: '1:698678244062:web:573697a8fc77751780c84f',
    messagingSenderId: '698678244062',
    projectId: 'consearch-52394',
    authDomain: 'consearch-52394.firebaseapp.com',
    storageBucket: 'consearch-52394.firebasestorage.app',
    measurementId: 'G-LP5PFPS4R1',
  );

}